### ISSUE TITLE
Consider relaxing pytest requirement?

### ISSUE THREAD

**Issue by JohnGiorgi** [danieldeutsch/repro#138]
`pytest` is currently pinned to exactly 6.2.4, which makes it a little tough to use packages (like `qaeval`) that depend on `sacrerouge` and therefore `repro` in different environments. Could this versioning be relaxed to make it easier to install `repro` in different environments? e.g. `pytest>=6.2.4`. Another option would be to move it to the `test_requirements` of the setup file (or move it under some `extra_requirements` named `dev` or `test` or w/e), assuming it's not needed for actually running any metrics.

**Comment by danieldeutsch** [comment]
Sorry for the late reply. I just relaxed the version and published 0.1.6 with the change.
